import "reflect-metadata";
import { container } from "tsyringe";
import { AdminService } from "../services/adminService";
import { AdminRepository } from "../repositories/adminRepository";
import { JobDesignationRepository } from "../repositories/jobDesignationRepository";
import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { UserRepository } from "../repositories/userRepository";
import { TechnicianRepository } from "../repositories/technicianRepository";
import { IadminRepository } from "../interfaces/Irepositories/IadminRepository";
import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IjwtService } from "../interfaces/Ijwt/Ijwt";
import { IadminService } from "../interfaces/Iservices/IadminService";
import { IjobDesignationRepository } from "../interfaces/Irepositories/IjobDesignationRepository";
import { IuserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ItechnicianRepository } from "../interfaces/Irepositories/ItechnicianRepository";
import { CloudinaryUploader } from "../utils/cloudinaryUploader";
import { IFileUploader } from "../interfaces/IfileUploader/IfileUploader";
import { ICategoryRepository } from "../interfaces/Irepositories/IcategoryRepository";
import { CategoryRepository } from "../repositories/categoryRepository";
import { IserviceRepository } from "../interfaces/Irepositories/IserviceRepository";
import { ServiceRepository } from "../repositories/serviceRepository";
import { IServiceService } from "../interfaces/Iservices/IserviceService";
import { ServiceServices } from "../services/serviceService";
import { IjobsService } from "../interfaces/Iservices/IjobsService";
import { JobService } from "../services/jobService";
import { TechnicianService } from "../services/technicianService";
import { ItechnicianService } from "../interfaces/Iservices/ItechnicianService";

container.registerSingleton<IadminService>("IadminService", AdminService);
container.registerSingleton<IadminRepository>("IadminRepository", AdminRepository);
container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IjwtService>("IjwtService", JWTService);
container.registerSingleton<IjobsService>("IjobsService",JobService);
container.registerSingleton<IjobDesignationRepository>("IjobDesignationRepository", JobDesignationRepository);
container.registerSingleton<IuserRepository>("IuserRepository", UserRepository);
container.registerSingleton<ItechnicianRepository>("ItechnicianRepository",TechnicianRepository);
container.registerSingleton<IFileUploader>("IFileUploader",CloudinaryUploader);
container.registerSingleton<ICategoryRepository>("ICategoryRepository",CategoryRepository);
container.registerSingleton<IserviceRepository>("IserviceRepository",ServiceRepository);
container.registerSingleton<IServiceService>("IServiceService",ServiceServices);
container.registerSingleton<ItechnicianService>("ItechnicianService",TechnicianService);