import "reflect-metadata";
import { container } from "tsyringe";
import { AdminAuthService } from "../services/adminService/adminAuthService";
import { AdminRepository } from "../repositories/adminRepository";
import { JobDesignationRepository } from "../repositories/jobDesignationRepository";
import { JobDesignationService } from "../services/adminService/jobDesignationService";
import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { UserManagementService } from "../services/adminService/userManagementService";
import { ApplicantManagementService } from "../services/adminService/applicantManagementService";
import { UserRepository } from "../repositories/userRepository";
import { TechnicianRepository } from "../repositories/technicianRepository";
import { IadminRepository } from "../interfaces/Irepositories/IadminRepository";
import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IjwtService } from "../interfaces/Ijwt/Ijwt";
import { IadminService } from "../interfaces/Iservices/IadminService/IadminAuthService";
import { IjobDesignationService } from "../interfaces/Iservices/IadminService/IjobDesignationService";
import { IjobDesignationRepository } from "../interfaces/Irepositories/IjobDesignationRepository";
import { IuserManagementService } from "../interfaces/Iservices/IadminService/IuserManagementService";
import { IuserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ItechnicianRepository } from "../interfaces/Irepositories/ItechnicianRepository";
import { IapplicantManagementService } from "../interfaces/Iservices/IadminService/IapplicantManagementService";
import { CategoryManagementService } from "../services/adminService/categoryManagementService";
import { ICategoryManagementService } from "../interfaces/Iservices/IadminService/IcategoryManagementService";
import { CloudinaryUploader } from "../utils/cloudinaryUploader";
import { IFileUploader } from "../interfaces/IfileUploader/IfileUploader";
import { ICategoryRepository } from "../interfaces/Irepositories/IcategoryRepository";
import { CategoryRepository } from "../repositories/categoryRepository";
import { IserviceManagementService } from "../interfaces/Iservices/IadminService/IserviceManagementService";
import { ServiceManagementService } from "../services/adminService/serviceManagementService";
import { IserviceRepository } from "../interfaces/Irepositories/IserviceRepository";
import { ServiceRepository } from "../repositories/serviceRepository";

container.registerSingleton<IadminService>("IadminService", AdminAuthService);
container.registerSingleton<IadminRepository>("IadminRepository", AdminRepository);
container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IjwtService>("IjwtService", JWTService);
container.registerSingleton<IjobDesignationService>("IjobDesignationService", JobDesignationService);
container.registerSingleton<IjobDesignationRepository>("IjobDesignationRepository", JobDesignationRepository);
container.registerSingleton<IuserRepository>("IuserRepository", UserRepository);
container.registerSingleton<IuserManagementService>("IuserManagementService", UserManagementService);
container.registerSingleton<IapplicantManagementService>("IapplicantManagementService",ApplicantManagementService);
container.registerSingleton<ItechnicianRepository>("ItechnicianRepository",TechnicianRepository);
container.registerSingleton<ICategoryManagementService>("ICategoryManagementService",CategoryManagementService);
container.registerSingleton<IFileUploader>("IFileUploader",CloudinaryUploader);
container.registerSingleton<ICategoryRepository>("ICategoryRepository",CategoryRepository);
container.registerSingleton<IserviceManagementService>("IserviceManagementService",ServiceManagementService);
container.registerSingleton<IserviceRepository>("IserviceRepository",ServiceRepository);