import "reflect-metadata";
import { container } from "tsyringe";

import { AuthService } from "../services/authService";
import { UserService } from "../services/userService";
import { TechnicianService } from "../services/technicianService";
import { AdminService } from "../services/adminService";
import { AddressService } from "../services/addressService";
import { TimeSlotService } from "../services/timeSlotService";
import { BookingService } from "../services/bookingService";
import { ChatService } from "../services/chatService";
import { OfferService } from "../services/offerService";
import { CouponService } from "../services/couponService";
import { NotificationService } from "../services/notificationService";
import { CategoryService } from "../services/categoryService";
import { WalletService } from "../services/walletService";
import { DesignationService } from "../services/designationService";
import { SubscriptionExpiryService } from "../services/subscriptionExpiryService";
import { WalletCreditService } from "../services/walletCreditService";
import { ApplicantService } from "../services/applicantService";
import { ServiceServices } from "../services/serviceService";
import { SubscriptionPlanService } from "../services/subscriptionPlanService";

import { UserRepository } from "../repositories/userRepository";
import { TechnicianRepository } from "../repositories/technicianRepository";
import { AdminRepository } from "../repositories/adminRepository";
import { AddressRepository } from "../repositories/addressRepository";
import { BookingRepository } from "../repositories/bookingRespository";
import { WalletRepository } from "../repositories/walletRepository";
import { WalletTransactionRepository } from "../repositories/walletTransactionRepository";
import { PaymentRepository } from "../repositories/paymentRepository";
import { ChatRepository } from "../repositories/chatRepository";
import { OfferRepository } from "../repositories/offerRepository";
import { CouponRepository } from "../repositories/couponRepository";
import { NotificationRepository } from "../repositories/notificationRepository";
import { DesignationRepository } from "../repositories/designationRepository";
import { TimeSlotRepository } from "../repositories/timeSlotRepository";
import { RatingRepository } from "../repositories/ratingRepository";
import { CategoryRepository } from "../repositories/categoryRepository";
import { ServiceRepository } from "../repositories/serviceRepository";
import { SubscriptionPlanRepository } from "../repositories/subscriptionPlanRepository";
import { SubscriptionPlanHistoryRepository } from "../repositories/subscriptionPlanHistoryRepository";

import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { EmailService } from "../utils/email";
import { EmailTemplateService } from "../utils/emailTemplates";
import { OTPService } from "../utils/otp";
import { RedisService } from "../utils/redis";
import { CloudinaryUploader } from "../utils/cloudinaryUploader";
import { CronService } from "../utils/cron";

import { IAuthService } from "../interfaces/Iservices/IauthService";
import { IUserService } from "../interfaces/Iservices/IuserService";
import { ITechnicianService } from "../interfaces/Iservices/ItechnicianService";
import { IAdminService } from "../interfaces/Iservices/IadminService";
import { IAddressService } from "../interfaces/Iservices/IaddressService";
import { ITimeSlotService } from "../interfaces/Iservices/ItimeSlotService";
import { IBookingService } from "../interfaces/Iservices/IbookingService";
import { IChatService } from "../interfaces/Iservices/IchatService";
import { IOfferService } from "../interfaces/Iservices/IofferService";
import { ICouponService } from "../interfaces/Iservices/IcouponService";
import { INotificationService } from "../interfaces/Iservices/InotificationService";
import { ICategoryService } from "../interfaces/Iservices/IcategoryService";
import { IWalletService } from "../interfaces/Iservices/IwalletService";
import { IDesignationService } from "../interfaces/Iservices/IdesignationService";
import { ISubscriptionExpiryService } from "../interfaces/Iservices/IsubscriptionExpiryService";
import { IWalletCreditService } from "../interfaces/Iservices/IwalletCreditService";
import { IApplicantService } from "../interfaces/Iservices/IapplicantService";
import { IServiceService } from "../interfaces/Iservices/IserviceService";
import { ISubscriptionPlanService } from "../interfaces/Iservices/IsubscriptionPlanService";

import { IUserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ITechnicianRepository } from "../interfaces/Irepositories/ItechnicianRepository";
import { IAdminRepository } from "../interfaces/Irepositories/IadminRepository";
import { IAddressRepository } from "../interfaces/Irepositories/IaddressRepository";
import { IBookingRepository } from "../interfaces/Irepositories/IbookingRespository";
import { IWalletRepository } from "../interfaces/Irepositories/IwalletRepository";
import { IWalletTransactionRepository } from "../interfaces/Irepositories/IwalletTransactionRepository";
import { IPaymentRepository } from "../interfaces/Irepositories/IpaymentRepository";
import { IChatRepository } from "../interfaces/Irepositories/IchatRepository";
import { IOfferRepository } from "../interfaces/Irepositories/IofferRepository";
import { ICouponRepository } from "../interfaces/Irepositories/IcouponRepository";
import { INotificationRepository } from "../interfaces/Irepositories/InotificationRepository";
import { IDesignationRepository } from "../interfaces/Irepositories/IdesignationRepository";
import { ITimeSlotRepository } from "../interfaces/Irepositories/ItimeSlotRepository";
import { IRatingRepository } from "../interfaces/Irepositories/IratingRepository";
import { ICategoryRepository } from "../interfaces/Irepositories/IcategoryRepository";
import { IServiceRepository } from "../interfaces/Irepositories/IserviceRepository";
import { ISubscriptionPlanRepository } from "../interfaces/Irepositories/IsubscriptionPlanRepository";
import { ISubscriptionPlanHistoryRepository } from "../interfaces/Irepositories/IsubscriptionPlanHistoryRepository";

import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IJwtService } from "../interfaces/Ijwt/Ijwt";
import { IEmailService } from "../interfaces/Iemail/Iemail";
import { IemailTemplateService } from "../interfaces/Iemail/IemailTemplate";
import { IOTPService } from "../interfaces/Iotp/IOTP";
import { IRedisService } from "../interfaces/Iredis/Iredis";
import { IFileUploader } from "../interfaces/IfileUploader/IfileUploader";
import { ICronService } from "../interfaces/Icron/Icron";
import { IPartService } from "../interfaces/Iservices/IpartService";
import { PartsService } from "../services/partService";
import { IPartsRepository } from "../interfaces/Irepositories/IpartRepository";
import { PartsRepository } from "../repositories/partsRepository";
import { IReservationExpiryService } from "../interfaces/Iservices/IreservationExpiryService";
import { ReservationExpiryService } from "../services/reservationExpiryService";
import { IBookingExpiryService } from "../interfaces/Iservices/IbookingExpiryService";
import { BookingExpiryService } from "../services/BookingExpiryService";

container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IJwtService>("IJwtService", JWTService);
container.registerSingleton<IOTPService>("IOTPService", OTPService);
container.registerSingleton<IRedisService>("IRedisService", RedisService);
container.registerSingleton<IEmailService>("IEmailService", EmailService);
container.registerSingleton<IemailTemplateService>("IemailTemplateService", EmailTemplateService);
container.registerSingleton<IFileUploader>("IFileUploader", CloudinaryUploader);
container.registerSingleton<ICronService>("ICronService", CronService);

container.registerSingleton<IAuthService>("IAuthService", AuthService);

container.registerSingleton<IUserRepository>("IUserRepository", UserRepository);
container.registerSingleton<ITechnicianRepository>("ITechnicianRepository", TechnicianRepository);
container.registerSingleton<IAdminRepository>("IAdminRepository", AdminRepository);
container.registerSingleton<IAddressRepository>("IAddressRepository", AddressRepository);
container.registerSingleton<IBookingRepository>("IBookingRepository", BookingRepository);
container.registerSingleton<IWalletRepository>("IWalletRepository", WalletRepository);
container.registerSingleton<IWalletTransactionRepository>("IWalletTransactionRepository", WalletTransactionRepository);
container.registerSingleton<IPaymentRepository>("IPaymentRepository", PaymentRepository);
container.registerSingleton<IChatRepository>("IChatRepository", ChatRepository);
container.registerSingleton<IOfferRepository>("IOfferRepository", OfferRepository);
container.registerSingleton<ICouponRepository>("ICouponRepository", CouponRepository);
container.registerSingleton<INotificationRepository>("INotificationRepository", NotificationRepository);
container.registerSingleton<IDesignationRepository>("IJobDesignationRepository", DesignationRepository);
container.registerSingleton<IDesignationRepository>("IDesignationRepository", DesignationRepository);
container.registerSingleton<ITimeSlotRepository>("ITimeSlotRepository", TimeSlotRepository);
container.registerSingleton<IRatingRepository>("IRatingRepository", RatingRepository);
container.registerSingleton<ICategoryRepository>("ICategoryRepository", CategoryRepository);
container.registerSingleton<IServiceRepository>("IServiceRepository", ServiceRepository);
container.registerSingleton<ISubscriptionPlanRepository>("ISubscriptionPlanRepository", SubscriptionPlanRepository);
container.registerSingleton<ISubscriptionPlanHistoryRepository>("ISubscriptionPlanHistoryRepository", SubscriptionPlanHistoryRepository);

container.registerSingleton<IUserService>("IUserService", UserService);
container.registerSingleton<ITechnicianService>("ITechnicianService", TechnicianService);
container.registerSingleton<IAdminService>("IAdminService", AdminService);
container.registerSingleton<IAddressService>("IAddressService", AddressService);
container.registerSingleton<ITimeSlotService>("ITimeSlotService", TimeSlotService);
container.registerSingleton<IBookingService>("IBookingService", BookingService);
container.registerSingleton<IChatService>("IChatService", ChatService);
container.registerSingleton<IChatService>("IchatService", ChatService);
container.registerSingleton<IOfferService>("IOfferService", OfferService);
container.registerSingleton<ICouponService>("ICouponService", CouponService);
container.registerSingleton<INotificationService>("INotificationService", NotificationService);
container.registerSingleton<ICategoryService>("ICategoryService", CategoryService);
container.registerSingleton<IWalletService>("IWalletService", WalletService);
container.registerSingleton<IDesignationService>("IjobsService", DesignationService);
container.registerSingleton<IDesignationService>("IDesignationService", DesignationService);
container.registerSingleton<ISubscriptionExpiryService>("ISubscriptionExpiryService", SubscriptionExpiryService);
container.registerSingleton<IWalletCreditService>("IWalletCreditService", WalletCreditService);
container.registerSingleton<IReservationExpiryService>("IReservationExpiryService",ReservationExpiryService);
container.registerSingleton<IBookingExpiryService>("IBookingExpiryService",BookingExpiryService);
container.registerSingleton<IApplicantService>("IApplicantService", ApplicantService);
container.registerSingleton<IServiceService>("IServiceService", ServiceServices);
container.registerSingleton<ISubscriptionPlanService>("ISubscriptionPlanService", SubscriptionPlanService);
container.registerSingleton<IPartService>("IPartService",PartsService);
container.registerSingleton<IPartsRepository>("IPartsRepository",PartsRepository);

export { container };