import "reflect-metadata";
import { container } from "tsyringe";
import { UserAuthService } from "../services/userService/userAuthService";
import { UserRepository } from "../repositories/userRepository";
import { TempUserRepository } from "../repositories/tempRepositories/tempUserRepository";
import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { EmailService } from "../utils/email";
import { EmailTemplateService } from "../utils/emailTemplates";
import { OTPService } from "../utils/otp";
import { RedisService } from "../utils/redis";
import { IuserAuthService } from "../interfaces/Iservices/IuserService/IuserAuthService";
import { IuserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ItempUserRepository } from "../interfaces/Irepositories/ItempUserRepository";
import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IjwtService } from "../interfaces/Ijwt/Ijwt";
import { IemailService } from "../interfaces/Iemail/Iemail";
import { IemailTemplateService } from "../interfaces/Iemail/IemailTemplate";
import { IOTPService } from "../interfaces/Iotp/IOTP";
import { IredisService } from "../interfaces/Iredis/Iredis";

container.registerSingleton<IuserAuthService>("IuserAuthService", UserAuthService);
container.registerSingleton<IuserRepository>("IuserRepository", UserRepository);
container.registerSingleton<ItempUserRepository>("ItempUserRepository", TempUserRepository);
container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IjwtService>("IjwtService", JWTService);
container.registerSingleton<IOTPService>("IOTPService", OTPService);
container.registerSingleton<IredisService>("IredisService", RedisService);
container.registerSingleton<IemailService>("IemailService", EmailService);
container.registerSingleton<IemailTemplateService>("IemailTemplateService", EmailTemplateService);