import "reflect-metadata";
import { container } from "tsyringe";
import { UserService } from "../services/userService";
import { UserRepository } from "../repositories/userRepository";
import { TempUserRepository } from "../repositories/tempRepositories/tempUserRepository";
import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { EmailService } from "../utils/email";
import { EmailTemplateService } from "../utils/emailTemplates";
import { OTPService } from "../utils/otp";
import { RedisService } from "../utils/redis";
import { IuserService } from "../interfaces/Iservices/IuserService";
import { IuserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ItempUserRepository } from "../interfaces/Irepositories/ItempUserRepository";
import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IjwtService } from "../interfaces/Ijwt/Ijwt";
import { IemailService } from "../interfaces/Iemail/Iemail";
import { IemailTemplateService } from "../interfaces/Iemail/IemailTemplate";
import { IOTPService } from "../interfaces/Iotp/IOTP";
import { IredisService } from "../interfaces/Iredis/Iredis";
import { IFileUploader } from "../interfaces/IfileUploader/IfileUploader";
import { CloudinaryUploader } from "../utils/cloudinaryUploader";
import { IAddressRepository } from "../interfaces/Irepositories/IaddressRepository";
import { AddressRepository } from "../repositories/addressRepository";
import { IAddressService } from "../interfaces/Iservices/IaddressService";
import { AddressService } from "../services/addressService";
import { ITimeSlotService } from "../interfaces/Iservices/ItimeSlotService";
import { TimeSlotService } from "../services/timeSlotService";
import { ItechnicianService } from "../interfaces/Iservices/ItechnicianService";
import { TechnicianService } from "../services/technicianService";
import { IbookingService } from "../interfaces/Iservices/IbookingService";
import { IbookingRepository } from "../interfaces/Irepositories/IbookingRespository";
import { BookingService } from "../services/bookingService";
import { BookingRepository } from "../repositories/bookingRespository";
import { IWalletRepository } from "../interfaces/Irepositories/IwalletRepository";
import { WalletRepository } from "../repositories/walletRepository";
import { IWalletTransactionRepository } from "../interfaces/Irepositories/IwalletTransactionRepository";
import { WalletTransactionRepository } from "../repositories/walletTransactionRepository";
import { IPaymentRepository } from "../interfaces/Irepositories/IpaymentRepository";
import { PaymentRepository } from "../repositories/paymentRepository";


container.registerSingleton<IuserService>("IuserService",UserService);
container.registerSingleton<IuserRepository>("IuserRepository", UserRepository);
container.registerSingleton<ItempUserRepository>("ItempUserRepository", TempUserRepository);
container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IjwtService>("IjwtService", JWTService);
container.registerSingleton<IOTPService>("IOTPService", OTPService);
container.registerSingleton<IredisService>("IredisService", RedisService);
container.registerSingleton<IemailService>("IemailService", EmailService);
container.registerSingleton<IemailTemplateService>("IemailTemplateService", EmailTemplateService);
container.registerSingleton<IFileUploader>("IFileUploader", CloudinaryUploader);
container.registerSingleton<IAddressRepository>("IAddressRepository",AddressRepository);
container.registerSingleton<IAddressService>("IAddressService",AddressService);
container.registerSingleton<ITimeSlotService>("ITimeSlotService",TimeSlotService);
container.registerSingleton<ItechnicianService>("ItechnicianService",TechnicianService);
container.registerSingleton<IbookingService>("IbookingService",BookingService);
container.registerSingleton<IbookingRepository>("IbookingRepository",BookingRepository);
container.registerSingleton<IWalletRepository>("IWalletRepository",WalletRepository);
container.registerSingleton<IWalletTransactionRepository>("IWalletTransactionRepository",WalletTransactionRepository)
container.registerSingleton<IPaymentRepository>("IPaymentRepository",PaymentRepository);