import "reflect-metadata";
import { container } from "tsyringe";
import { UserService } from "../services/userService";
import { UserRepository } from "../repositories/userRepository";
import { TempUserRepository } from "../repositories/tempRepositories/tempUserRepository";
import { PasswordHasher } from "../utils/password";
import { JWTService } from "../utils/jwt";
import { EmailService } from "../utils/email";
import { EmailTemplateService } from "../utils/emailTemplates";
import { OTPService } from "../utils/otp";
import { RedisService } from "../utils/redis";
import { IUserService } from "../interfaces/Iservices/IuserService";
import { IUserRepository } from "../interfaces/Irepositories/IuserRepository";
import { ITempUserRepository } from "../interfaces/Irepositories/ItempUserRepository";
import { IPasswordHasher } from "../interfaces/IpasswordHasher/IpasswordHasher";
import { IJwtService } from "../interfaces/Ijwt/Ijwt";
import { IEmailService } from "../interfaces/Iemail/Iemail";
import { IemailTemplateService } from "../interfaces/Iemail/IemailTemplate";
import { IOTPService } from "../interfaces/Iotp/IOTP";
import { IRedisService } from "../interfaces/Iredis/Iredis";
import { IFileUploader } from "../interfaces/IfileUploader/IfileUploader";
import { CloudinaryUploader } from "../utils/cloudinaryUploader";
import { IAddressRepository } from "../interfaces/Irepositories/IaddressRepository";
import { AddressRepository } from "../repositories/addressRepository";
import { IAddressService } from "../interfaces/Iservices/IaddressService";
import { AddressService } from "../services/addressService";
import { ITimeSlotService } from "../interfaces/Iservices/ItimeSlotService";
import { TimeSlotService } from "../services/timeSlotService";
import { ITechnicianService } from "../interfaces/Iservices/ItechnicianService";
import { TechnicianService } from "../services/technicianService";
import { IBookingService } from "../interfaces/Iservices/IbookingService";
import { IBookingRepository } from "../interfaces/Irepositories/IbookingRespository";
import { BookingService } from "../services/bookingService";
import { BookingRepository } from "../repositories/bookingRespository";
import { IWalletRepository } from "../interfaces/Irepositories/IwalletRepository";
import { WalletRepository } from "../repositories/walletRepository";
import { IWalletTransactionRepository } from "../interfaces/Irepositories/IwalletTransactionRepository";
import { WalletTransactionRepository } from "../repositories/walletTransactionRepository";
import { IPaymentRepository } from "../interfaces/Irepositories/IpaymentRepository";
import { PaymentRepository } from "../repositories/paymentRepository";
import { IChatService } from "../interfaces/Iservices/IchatService";
import { IChatRepository } from "../interfaces/Irepositories/IchatRepository";
import { ChatService } from "../services/chatService";
import { ChatRepository } from "../repositories/chatRepository";


container.registerSingleton<IUserService>("IUserService",UserService);
container.registerSingleton<IUserRepository>("IUserRepository", UserRepository);
container.registerSingleton<ITempUserRepository>("ITempUserRepository", TempUserRepository);
container.registerSingleton<IPasswordHasher>("IPasswordHasher", PasswordHasher);
container.registerSingleton<IJwtService>("IJwtService", JWTService);
container.registerSingleton<IOTPService>("IOTPService", OTPService);
container.registerSingleton<IRedisService>("IRedisService", RedisService);
container.registerSingleton<IEmailService>("IEmailService", EmailService);
container.registerSingleton<IemailTemplateService>("IemailTemplateService", EmailTemplateService);
container.registerSingleton<IFileUploader>("IFileUploader", CloudinaryUploader);
container.registerSingleton<IAddressRepository>("IAddressRepository",AddressRepository);
container.registerSingleton<IAddressService>("IAddressService",AddressService);
container.registerSingleton<ITimeSlotService>("ITimeSlotService",TimeSlotService);
container.registerSingleton<ITechnicianService>("ITechnicianService",TechnicianService);
container.registerSingleton<IBookingService>("IBookingService",BookingService);
container.registerSingleton<IBookingRepository>("IBookingRepository",BookingRepository);
container.registerSingleton<IWalletRepository>("IWalletRepository",WalletRepository);
container.registerSingleton<IWalletTransactionRepository>("IWalletTransactionRepository",WalletTransactionRepository)
container.registerSingleton<IPaymentRepository>("IPaymentRepository",PaymentRepository);
container.registerSingleton<IChatService>("IChatService",ChatService);
container.registerSingleton<IChatRepository>("IChatRepository",ChatRepository)