
export enum EmailType {
  SIGNUP_OTP = 'SIGNUP_OTP',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
  VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED'
}

export const APP_NAME = "Fixify";
